name: Docker Image CI

on:
  push:
    branches: [ main, test_actions ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./apps/redis/ --file ./apps/redis/Dockerfile --tag redis-x86:$(date +%s)
